language: bash
os: linux
dist: bionic

services:
  - docker 

git:
  depth: 10
  submodules: true

before_script:
  - docker version
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build --pull --build-arg BUILD_ID="$(git log --oneline --sparse --decorate --graph -n10)" -t saidsef/alpine-jenkins-dockerfile:$TRAVIS_BRANCH .

after_script:
  - ./script/deploy.sh

notifications:
  email: true
