---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  labels:
    name: jenkins
    app: jenkins
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: $(HOST)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 80