---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/jenkins.yml
- base/service.yml
- base/ingress.yml
- base/sa.yml
- base/role.yml
- base/role-binding.yml

commonAnnotations:
  app.kubernetes.io/managed-by: kustomizer
  app.kubernetes.io/part-of: jenkins

images:
- name: jenkins
  newName: docker.io/saidsef/alpine-jenkins-dockerfile
  newTag: v2023.08

vars:
- fieldref: {}
  name: HOST
  objref:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: jenkins
