apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/
- nginx/

commonAnnotations:
  app.kubernetes.io/managed-by: kustomizer
  app.kubernetes.io/part-of: jenkins

images:
- name: jenkins
  newName: docker.io/saidsef/alpine-jenkins-dockerfile
  newTag: v2024.03
