---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
    app: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins-main
  ports:
    - name: tcp-jenkins
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: tcp-monitoring
      port: 8081
      protocol: TCP
      targetPort: 8081
