apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/component: controller
automountServiceAccountToken: true
