---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
    app: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
    - name: tcp-jenkins
      port: 80
      protocol: TCP
      targetPort: tcp-jenkins
