apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/
- ../nginx/

commonAnnotations:
  app.kubernetes.io/managed-by: kustomizer

images:
- name: jenkins-main
  newName: docker.io/saidsef/alpine-jenkins-dockerfile
  newTag: merge


patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: preview.saidsef.co.uk
  target:
    kind: Ingress
    name: jenkins
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: docker.io/saidsef/alpine-jenkins-dockerfile:merge
  target:
    group: apps
    kind: StatefulSet
    name: jenkins-main
    version: v1
